config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" 
  root to: "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # regenerate this controller with
  # rails generate hot_glue:scaffold Image --include='name:avatar' --gd --attachments='avatar{thumb||direct|dropzone}'

  helper :hot_glue
  include HotGlue::ControllerHelper

  
  before_action :load_image, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol == :turbo_stream }
  
  
  def load_image
    @image = Image.find(params[:id])
  end
  

  def load_all_images
    @images = Image.page(params[:page]).includes(:avatar_attachment)
  end

  def index
    load_all_images
  end

  def new
    @image = Image.new()
   
  end

  def create
 
    modified_params = modify_date_inputs_on_params(image_params.dup)
    @image = Image.create(modified_params)

    if @image.save
      flash[:notice] = "Successfully created #{@image.name}"
      load_all_images
      render :create
    else
      flash[:alert] = "Oops, your image could not be created. #{@hawk_alarm}"
      render :create, status: :unprocessable_entity
    end
  end


  def edit
    render :edit
  end

  def update
 
    
    modified_params = modify_date_inputs_on_params(image_params.dup)

    

    if @image.update(modified_params)
      
      flash[:notice] = (flash[:notice] || "") << "Saved #{@image.name}"
      flash[:alert] = @hawk_alarm if @hawk_alarm
      render :update
    else
      flash[:alert] = (flash[:alert] || "") << "Image could not be saved. #{@hawk_alarm}"
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      @image.destroy
    rescue StandardError => e
      flash[:alert] = 'Image could not be deleted.'
    end
    load_all_images
  end

  def image_params
    params.require(:image).permit([:name, :avatar])
  end

  def namespace
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_errors.erb
<%= turbo_frame_tag "errors" do %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/images/_form.erb
<div class="row">
  <div class='col-md-5 cell--image--name' >  
    <span class='<%= "alert-danger" if image.errors.details.keys.include?(:name) %>'  style="display: inherit;"  >
        <%= f.text_field :name, value: image.name, autocomplete: 'off', size: 40, class: 'form-control', type: '' %>
       
      
      <label class='small form-text text-muted'>Name</label>
    </span>
    <br />
  </div>
  <div class='col-md-5 cell--image--avatar' >  
    <span class='<%= "alert-danger" if image.errors.details.keys.include?(:avatar) %>'  style="display: inherit;"  >
      <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1">
        <%= image.avatar.attached? && image.avatar.variable? ? image_tag(image.avatar.variant(:thumb)) : '' %><br />
      <%= f.file_field :avatar , direct_upload: true , "data-dropzone-target": "input"%>
      </div>
      <label class='small form-text text-muted'>Avatar</label>
    </span>
    <br />
  </div>

  <div class="col-md-2">
    <%= link_to "Cancel", images_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/images/_line.erb
<%= turbo_frame_tag "__#{ dom_id(image) }" do  %>
  <div class='row' data-id='<%= image.id %>' data-edit='false'>
    <%= render partial: 'images/show', locals: { image: image } %>

  </div>
<% end %>

app/views/images/_list.erb
<%= turbo_frame_tag "__images-list"   do %>
  <div class="container ">
    
      <h4>
        IMAGES
      </h4>
    

    <%= render partial: "images/new_button", locals: {} %><br />

    
      
        <div class="row ">
          <div class='col-sm-5' heading--image--name >Name</div>
<div class='col-sm-5' heading--image--avatar >Avatar</div>

          

          <div class=' scaffold-col-heading scaffold-col-heading-buttons col-sm-5' >
          </div>
        </div>
      

      <% if images.empty? %>
    <div>
        None
    </div>
      <% end %>
      <% images.each do |image| %>
        <%= render partial: 'images/line', locals: {image: image}
            .merge(defined?(nested_for) ? {nested_for: nested_for} : {})
      
        %>
      <% end %>
    <% if images.respond_to?(:total_pages) %><%= paginate(images) %> <% end %>
  
  </div>
<% end %>

app/views/images/_new_button.erb
<%= turbo_frame_tag "__image-new" do %>
  <div>
    <%= link_to "New Image",  new_image_path, disable_with: "Loading...", class: "new-image-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/images/_new_form.erb
<%= turbo_frame_tag "__image-new" do %>
  <h3>
    New Image
  </h3>
  <%= form_with model:  image, url: images_path, method: :post do  |f| %>
    <%=  render partial: "images/form",
locals: { image: image, f: f} %>
 <% end %>
<% end %>

app/views/images/_show.erb
<div class='col-sm-5 image--name'> <%= image.name %></div>
<div class='col-sm-5 image--avatar'> <%= image.avatar.attached? && image.avatar.variable? ? image_tag(image.avatar.variant(:thumb)) : '' %></div>






<div class=" scaffold-line-buttons col-md-2" >
  

  
    <%= form_with url: image_path(image), html: {data: {'turbo-confirm': "Are you sure you want to delete #{ image.name }?"}, style: "display: inline-block;"}, method: :delete do |f| %>
      <%= f.submit "Delete".html_safe,  class: "delete-image-button btn btn-primary btn-sm" %>
    <% end %>
  

  
  <%= link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_image_path(image), disable_with: "Loading...", class: "edit-image-button btn btn-primary btn-sm" %>
  
</div>

app/views/images/create.turbo_stream.erb
<% if @image.errors.none? %>
  <%= turbo_stream.replace "__images-list" + "" do %>
  <%= render partial: "list", locals: {images: @images} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "__image__image-new" do %>
  <% if @image.errors.none? %>
  <%= render partial: "new_button", locals: {} %>
  <% else %>
  <%= render partial: "new_form", locals: {image: @image} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @image.errors.any? %>
  <%= render partial: "errors", locals: {resource: @image} %>
  <% end %>
<% end %>

app/views/images/destroy.turbo_stream.erb
<%= turbo_stream.replace "__images-list" + "" do %>
  <%= render partial: "list", locals: {images: @images } %>
<% end %>

app/views/images/edit.erb
<%= link_to "<i class='fa fa-arrow-circle-left  2x'></i> Back to list".html_safe, images_path %>

<%= turbo_frame_tag "__#{dom_id(@image)}" do  %>

  <div class="cell editable" style="position: relative;">

    <% if @image.errors.any? %>
      <%= render(partial: "errors", locals: {resource: @image }) %>
    <% end %>

    <h2>Editing <%= @image.name %></h2>
    <%= form_with model: @image, url: image_path(@image) do |f| %>
    <%=  render partial: "form",  locals: {:image => @image, f: f} %>
    <% end %>

  </div>

<% end %>

app/views/images/edit.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(image)}" do %>
  <%= render 'edit' %>
<% end %>

app/views/images/index.erb
<div class="container">
  <div class="row"> <div class="col-md-12">
  

  <%= render partial: 'images/list',
    locals: {images: @images} %>

  </div> </div>
</div>

app/views/images/new.erb
<%= render partial: "new_form", locals: {image: @image} %>

app/views/images/update.turbo_stream.erb
<%= turbo_stream.replace "__#{dom_id(@image)}" do %>
  <%= render partial: 'line', locals: {image: @image } %>
<% end %>

<%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @image.errors.any? %>
  <%= render partial: "errors", locals: {resource: @image} %>
  <% end %>
<% end %>

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HGAttachment4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <%= render partial: 'layouts/flash_notices' %>
  
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div data-controller="dropzone"></div>


<div data-controller="hello"></div>


<div data-controller="xyz"></div>